name: Snake Animation

on:
 schedule: # execute every 12 hours
  - cron: "* */12 * * *"
 workflow_dispatch:

jobs:
 build:
  name: Generate Snake Animation
  runs-on: ubuntu-latest
  steps:
   # Snake Animation
   - uses: <nome-da-acao-de-animacao>@master
    id: snake-gif
    with:
     github_user_name: pedromendonca2
     svg_out_path: ./github-contribution-grid-snake.svg

   - uses: crazy-max/ghaction-github-pages@v2.1.3
    with:
     target_branch: output
     build_dir: build
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
